# Generated by Django 5.0.6 on 2024-06-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='valor',
            new_name='valor_total',
        ),
    ]
