# Generated by Django 5.0.6 on 2024-06-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_rename_valor_item_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
