# Generated by Django 5.0.6 on 2024-06-07 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_alter_cliente_cep_alter_cliente_cpf'),
        ('produto', '0003_alter_produto_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('produtos', models.ManyToManyField(to='produto.produto')),
            ],
        ),
    ]
